/*
 * AdultStageAttributesCustomizer.java
 *
 * Created on September 26, 2017.
 */

package wts.models.DisMELS.IBMs.SnowCrab.Adult;

import wts.models.DisMELS.framework.LifeStageAttributesInterface;
import wts.models.DisMELS.gui.AttributesCustomizer;

/**
 * @author William Stockhausen
 */
public class AdultStageAttributesCustomizer extends AttributesCustomizer {

    private boolean showHorizPos = true;
    private boolean showVertPos = true;
    
    private AdultStageAttributes attributes = null;
    
    /**
     * Creates new customizer EggStageAttributesCustomizer
     */
    public AdultStageAttributesCustomizer() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        czrStandardAttributes = new wts.models.DisMELS.gui.AbstractLHSAttributes2Customizer();
        jPanel2 = new javax.swing.JPanel();
        jtfSize = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfWeight = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfGonadStage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(czrStandardAttributes, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Additional attributes"));

        jtfSize.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfSize.setText("0");
        jtfSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSizeActionPerformed(evt);
            }
        });

        jLabel1.setText("Size (cm)");

        jtfWeight.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfWeight.setText("0");
        jtfWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfWeightActionPerformed(evt);
            }
        });

        jLabel2.setText("Weight (kg)");
        jLabel2.setToolTipText("diameter in mm");

        jtfGonadStage.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfGonadStage.setText("0");
        jtfGonadStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfGonadStageActionPerformed(evt);
            }
        });

        jLabel3.setText("Gonad stage");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jtfSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .add(jtfWeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .add(jtfGonadStage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtfSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtfWeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtfGonadStage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSizeActionPerformed
        Double n = new Double(jtfSize.getText());
        attributes.setValue(attributes.PROP_size,n);
    }//GEN-LAST:event_jtfSizeActionPerformed

    private void jtfWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfWeightActionPerformed
        Double n = new Double(jtfWeight.getText());
        attributes.setValue(attributes.PROP_weight,n);
    }//GEN-LAST:event_jtfWeightActionPerformed

    private void jtfGonadStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfGonadStageActionPerformed
        Double n = new Double(jtfGonadStage.getText());
        attributes.setValue(attributes.PROP_gonadStage,n);
    }//GEN-LAST:event_jtfGonadStageActionPerformed

    @Override
    public void setObject(Object bean) {
        if (bean instanceof AdultStageAttributes) {
            setAttributes((AdultStageAttributes) bean);
        }
    }
    
    @Override
    public AdultStageAttributes getAttributes() {
        return attributes;
    }
    
    @Override
    public void setAttributes(LifeStageAttributesInterface newAtts) {
        if (newAtts instanceof AdultStageAttributes) {
            attributes = (AdultStageAttributes) newAtts;
            czrStandardAttributes.setObject(attributes);
            Double d = null;
            jtfSize.setText(attributes.getValue(attributes.PROP_size,d).toString());
            jtfWeight.setText(attributes.getValue(attributes.PROP_weight,d).toString());
            jtfGonadStage.setText(attributes.getValue(attributes.PROP_gonadStage,d).toString());
        }
    }
    
    @Override
    public void showHorizPos(boolean b) {
        czrStandardAttributes.showHorizPos(b);
        revalidate();
    }
    
    @Override
    public void showVertPos(boolean b) {
        czrStandardAttributes.showVertPos(b);
        revalidate();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private wts.models.DisMELS.gui.AbstractLHSAttributes2Customizer czrStandardAttributes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jtfGonadStage;
    private javax.swing.JTextField jtfSize;
    private javax.swing.JTextField jtfWeight;
    // End of variables declaration//GEN-END:variables
    
}
